### ISSUE TITLE
Cannot login in on linux ubuntu

### ISSUE THREAD

**Issue by dimitrikvirik** [DJetCloud/djet-codegen#80]
I enter username and password in .credentials.yaml and when I try load OpenApi it print: `Caused by: java.lang.Exception: Authentication failed. Please check username and password
	at pro.bilous.difhub.auth.CognitoWrapper.login(CognitoWrapper.kt:14)
	at pro.bilous.difhub.auth.Authorizer.authToken(Authorizer.kt:8)
	at pro.bilous.difhub.load.TokenReader.readAuth(TokenReader.kt:10)
	at pro.bilous.difhub.load.DifHubLoader.getAuthToken(DefLoader.kt:93)
	at pro.bilous.difhub.load.DefLoader.loadFromUrl(DefLoader.kt:46)
	at pro.bilous.difhub.load.DefLoader.load(DefLoader.kt:22)
	at pro.bilous.difhub.load.ModelLoader.loadString(ModelLoader.kt:70)
	at pro.bilous.difhub.load.ModelLoader.loadModels(ModelLoader.kt:44)
	at pro.bilous.difhub.load.ApplicationsLoader.loadAll(ApplicationsLoader.kt:28)
	at pro.bilous.difhub.convert.DifHubToSwaggerConverter.convertAll(DifHubToSwaggerConverter.kt:26)
	at pro.bilous.intellij.plugin.action.menu.DifHubLoadOpenApiAction.createOpenApiFiles(DifHubLoadOpenApiAction.kt:84)
	at pro.bilous.intellij.plugin.action.menu.DifHubLoadOpenApiAction.actionPerformed(DifHubLoadOpenApiAction.kt:44)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:272)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:264)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:98)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:98)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:515)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:545)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	... 22 more`
Also 
 `[AWT-EventQueue-0] ERROR pro.bilous.intellij.plugin.errorreport.PluginErrorReportSubmitter - Plugin failed with error: IdeaLoggingEvent[message=Do not request resource from classloader using path with leading slash, throwable=java.lang.IllegalArgumentException: /awssdk_config_override.json
	at com.intellij.util.lang.UrlClassLoader.doFindResource(UrlClassLoader.java:340)
	at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:298)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.amazonaws.util.ClassLoaderHelper.getResourceViaContext(ClassLoaderHelper.java:91)
	at com.amazonaws.util.ClassLoaderHelper.getResource(ClassLoaderHelper.java:70)
	at com.amazonaws.internal.config.InternalConfig.getResource(InternalConfig.java:294)
	at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:266)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:336)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:142)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:137)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:100)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:80)
	at com.amazonaws.ClientConfigurationFactory.getDefaultConfig(ClientConfigurationFactory.java:46)
	at com.amazonaws.ClientConfigurationFactory.getConfig(ClientConfigurationFactory.java:36)
	at com.amazonaws.client.builder.AwsClientBuilder.resolveClientConfiguration(AwsClientBuilder.java:169)
	at com.amazonaws.client.builder.AwsClientBuilder.access$000(AwsClientBuilder.java:54)
	at com.amazonaws.client.builder.AwsClientBuilder$SyncBuilderParams.<init>(AwsClientBuilder.java:505)
	at com.amazonaws.client.builder.AwsClientBuilder.getSyncClientParams(AwsClientBuilder.java:441)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at pro.bilous.difhub.j.AuthenticationHelper.PerformSRPAuthentication(AuthenticationHelper.java:161)
	at pro.bilous.difhub.auth.CognitoWrapper.login(CognitoWrapper.kt:13)
	at pro.bilous.difhub.auth.Authorizer.authToken(Authorizer.kt:8)
	at pro.bilous.difhub.load.TokenReader.readAuth(TokenReader.kt:10)
	at pro.bilous.difhub.load.DifHubLoader.getAuthToken(DefLoader.kt:93)
	at pro.bilous.difhub.load.DefLoader.loadFromUrl(DefLoader.kt:46)
	at pro.bilous.difhub.load.DefLoader.load(DefLoader.kt:22)
	at pro.bilous.difhub.load.ModelLoader.loadString(ModelLoader.kt:70)
	at pro.bilous.difhub.load.ModelLoader.loadModels(ModelLoader.kt:44)
	at pro.bilous.difhub.load.ApplicationsLoader.loadAll(ApplicationsLoader.kt:28)
	at pro.bilous.difhub.convert.DifHubToSwaggerConverter.convertAll(DifHubToSwaggerConverter.kt:26)
	at pro.bilous.intellij.plugin.action.menu.DifHubLoadOpenApiAction.createOpenApiFiles(DifHubLoadOpenApiAction.kt:84)
	at pro.bilous.intellij.plugin.action.menu.DifHubLoadOpenApiAction.actionPerformed(DifHubLoadOpenApiAction.kt:44)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:272)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:264)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:98)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:98)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:515)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:545)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)]
`

 IntelliJ IDEA 2021.2  Build #IC-212.4746.92 
- JDK: 11.0.11; VM: OpenJDK 64-Bit Server
-  OS: Linux 
-   Plugin to blame: DJet version: 1.0.0-alpha 
- Last Action: loadOpenApiSpec

**Comment by v-bilous** [comment]
@dimitrikvirik please attach ur `.credentials.yaml` file to the issue, but please replace ur password using `*` for security purpose.

**Comment by dimitrikvirik** [comment]
![image](https://user-images.githubusercontent.com/63537879/148046041-07300476-34e7-47ef-af8b-cc832d6e8d0f.png)
It show on IDE but not show in Files

**Comment by dimitrikvirik** [comment]
> @dimitrikvirik please attach ur `.credentials.yaml` file to the issue, but please replace ur password using `*` for security username: d.kvirikashvili@inforttech.com
password: *

**Comment by dimitrikvirik** [comment]
file is hidden

**Comment by dimitrikvirik** [comment]
In Metucat have wrong credentials
